spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://springboot-webservice.ca3w67jmyfwa.ap-northeast-2.rds.amazonaws.com:3306/webservice?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: kuyt1819
      password: 187f5391
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true