spring:
  profiles:
    active: local # 기본 환경 선택 

# local 환경
---
spring:
  datasource: 
    url: jdbc:mysql://localhost:3307/springwebservice?useTimezone=true&serverTimezone=UTC
    username: root 
    password: root 
  jpa: 
    database-platform: org.hibernate.dialect.MySQLDialect 
    hibernate: 
      format_sql: true
      ddl-auto: update 
      generate-ddl: true 
      show-sql: true

  
      