spring:
  profiles:
    active: local # 기본 환경 선택 

# local 환경
---
spring:
  data:
    maria:
      jdbc-url: springboot-webservice.ca3w67jmyfwa.ap-northeast-2.rds.amazonaws.com:3306/webservice?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: kuyt1819
      password: !187f5391
  jpa: 
    database-platform: org.hibernate.dialect.MySQLDialect 
    hibernate: 
      format_sql: true
      ddl-auto: update 
      generate-ddl: true 
      show-sql: true

      